# 上传文件大小
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 信息安全
security:
  # 防止XSS攻击
  xss:
    enable: true
    #排除链接
    excludes:
      - /login
      - /securitylogout
      - /images/*
      - /jquery/*
      - /layui/*
      - /css/*
      - /js/*
  #跨站点请求伪造
  csrf:
    enable: true
  #防SQL注入
  sql:
    enable: true

